### ISSUE TITLE
control reaches end of non-void function

### ISSUE THREAD

**Issue by jrw429** [GabrielNotman/RTCCounter#1]
No return is defined if "_configured" is not set.

`uint32_t RTCCounter::getAlarmY2kEpoch()
{
  uint32_t alarm = 0;

  if (_configured) {
    alarm = RTC->MODE0.COMP[0].reg;
  }

  return alarm;
}
`

**Comment by GabrielNotman** [comment]
@jrw429 Thanks for your input. I have addressed this in v1.0.1.
